"""update_booking

Revision ID: 21c2b039297b
Revises: c8413bc7a7e8
Create Date: 2026-05-13 10:39:48.068898

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "21c2b039297b"
down_revision: Union[str, Sequence[str], None] = "c8413bc7a7e8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "booking", sa.Column("hotel_id", sa.Integer(), nullable=False)
    )
    op.create_foreign_key(None, "booking", "hotels", ["hotel_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "booking", type_="foreignkey")
    op.drop_column("booking", "hotel_id")
    # ### end Alembic commands ###
