"""change name in user

Revision ID: bae9751cabdf
Revises: 97de99d9702d
Create Date: 2026-02-06 18:10:02.724059

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "bae9751cabdf"
down_revision: Union[str, Sequence[str], None] = "97de99d9702d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("firstname", sa.String(length=100), nullable=False)
    )
    op.drop_column("users", "firsname")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "firsname",
            sa.VARCHAR(length=100),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("users", "firstname")
    # ### end Alembic commands ###
